const MK=['Alta calma','Alta volátil','Lateral calma','Lateral volátil','Baixa calma','Baixa volátil'];
const ERR=['Nenhum','Entrei por dica/emoção (fora do sistema)','Não saí no stop','Risco grande demais','Saí cedo por emoção','Não segui minha rotina','Operei fora do tipo de mercado','Foquei na entrada, não no risco/retorno','Entrei sem saída predeterminada','Precisava estar certo (realizei cedo/segurei perda)','Operei demais (perdi o controle)','Outro'];
const ESTR=['Compra de call','Compra de put','Venda coberta de call','Venda de put','Trava de alta','Trava de baixa','Financiamento / collar','Straddle / strangle','Borboleta / condor','Calendário','Outra'];
const CATS=['Plano de trade','Gestão de risco','Rotina','Psicologia'];
const SEED=[[0,'Só entro com setup do meu sistema (nunca por dica ou emoção)'],[0,'Defino a saída predeterminada antes de entrar'],[0,'Só opero o tipo de mercado para o qual meu sistema foi feito'],[1,'Defino o stop inicial (1R) antes de entrar'],[1,'Risco máximo de 1% do capital por trade'],[1,'Só pego trade com potencial de pelo menos 3R'],[1,'Saio quando o stop é atingido'],[2,'Faço autoavaliação e ensaio mental antes de abrir o mercado'],[2,'Registro todo trade com seu R-múltiplo'],[2,'Faço o debriefing no fim do dia'],[3,'Assumo a responsabilidade pelo resultado, sem culpar o mercado'],[3,'Aceito a perda no stop: não preciso estar certo']];
const $=s=>document.querySelector(s),uid=()=>Math.random().toString(36).slice(2,10),sum=a=>a.reduce((x,y)=>x+y,0),avg=a=>a.length?sum(a)/a.length:0;
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const f2=n=>n==null||!isFinite(n)?'–':n.toFixed(2).replace('.',','),fr=r=>(r>0?'+':'')+f2(r)+'R',pc=x=>Math.round(x*100)+'%',cls=n=>n>0?'g':n<0?'r':'';
const money=n=>n==null?'–':n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const opt=(a,v)=>a.map(x=>{const[k,l]=Array.isArray(x)?x:[x,x];return `<option value="${esc(k)}"${k==v?' selected':''}>${esc(l)}</option>`}).join('');
const loc=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*6e4).toISOString()};
const fdt=s=>s.slice(8,10)+'/'+s.slice(5,7)+' '+s.slice(11,16);
let S={trades:[],days:{},rules:[],seed:0},tab='home',T=null,orig={},isNew=0,delArm=0,D=loc().slice(0,10),db=null,M={},U={},st,PER='all',AUTO=0,TIPO='all',OPEN={},QM=0,VW={},LT='trades',SV=0,DV='ed',DX=null,LF={f:'all',q:''},CH={},SESS=null,AM='in',RECOV=null,SY={msg:'',email:''},sT;
const inPer=dt=>{if(PER==='all')return 1;const d=dt.slice(0,10),t=loc().slice(0,10);if(PER==='hoje')return d===t;if(PER==='mes')return d.slice(0,7)===t.slice(0,7);const c=new Date(Date.now()-(PER==='7'?7:30)*864e5);return d>=new Date(c-c.getTimezoneOffset()*6e4).toISOString().slice(0,10)};
const tipoSel=()=>`<label>Tipo<select id="tp">${opt([['all','Todos'],['D','Só day trade'],['S','Só swing'],['O','Só opções']],TIPO)}</select></label>`;
const sym=s=>{s=s.trim().toUpperCase();return s.includes(':')?s:'BMFBOVESPA:'+s};
const perSel=()=>`<label>Período<select id="per">${opt([['all','Tudo'],['hoje','Hoje'],['7','Últimos 7 dias'],['30','Últimos 30 dias'],['mes','Este mês']],PER)}</select></label>`;
const open=()=>new Promise(r=>{try{const q=indexedDB.open('diario-trader',1);q.onupgradeneeded=()=>{q.result.createObjectStore('kv');q.result.createObjectStore('img')};q.onsuccess=()=>{db=q.result;r()};q.onerror=()=>r()}catch(e){r()}});
const idb=(s,m,...a)=>new Promise(r=>{if(!db)return r();try{const q=db.transaction(s,m==='get'?'readonly':'readwrite').objectStore(s)[m](...a);q.onsuccess=()=>r(q.result);q.onerror=()=>r()}catch(e){r()}});
const persist=()=>{clearTimeout(st);st=setTimeout(()=>idb('kv','put',S,'s'),250)},save=()=>{S.mt=Date.now();SV=Date.now();persist();syncSoon();svUi()};
const shrink=f=>new Promise(r=>{const i=new Image();i.onload=()=>{const k=Math.min(1,1100/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=i.width*k;c.height=i.height*k;c.getContext('2d').drawImage(i,0,0,c.width,c.height);c.toBlob(r,'image/jpeg',.7)};i.onerror=()=>r(null);i.src=URL.createObjectURL(f)});
async function fillImgs(){for(const e of document.querySelectorAll('img[data-img]')){const id=e.dataset.img;if(!U[id]){const b=M[id]||await idb('img','get',id);if(b)U[id]=URL.createObjectURL(b)}if(U[id])e.src=U[id]}}
const isOpen=t=>!(t.exit!==''&&t.exit!=null&&isFinite(+t.exit));
function calc(t){const d=t.side==='C'?1:-1,pv=+t.pv||1,q=+t.qty||0,e=+t.entry,s=+t.stop,x=+t.exit,has=t.exit!==''&&t.exit!=null&&isFinite(x),risk=Math.abs(e-s)*q*pv,pl=has?(x-e)*d*q*pv-(+t.cost||0):null,r=has&&risk>0?pl/risk:null,rr=t.target!==''&&t.target!=null&&e!==s&&isFinite(+t.target)?Math.abs(+t.target-e)/Math.abs(e-s):null;return{risk,pl,r,rr}}
/* ---------- Trades ---------- */
function card(t){const c=calc(t),p=t.pplan||t.pin||t.pout;return `<div class="card row" data-a="edit" data-id="${t.id}" data-s="${esc(((t.ativo||'')+' '+(t.setup||'')).toLowerCase())}"><div class="th">${p?`<img data-img="${p}">`:'📈'}</div><div class="fl"><b>${esc(t.ativo)||'—'}</b> · ${t.tipo==='O'?(t.side==='C'?'Comprado':'Lançado'):(t.side==='C'?'Compra':'Venda')}<div class="mut sm">${fdt(t.dt)}${t.tipo==='O'&&t.strike?' · '+(t.ot==='P'?'Put':'Call')+' '+esc(t.strike):''}${t.setup?' · '+esc(t.setup):''}</div>${t.err&&t.err!=='Nenhum'?'<span class="tag">⚠ erro</span>':''}${t.rules==='n'?'<span class="tag">fora das regras</span>':''}</div><div class="rt ${cls(c.r)}">${c.r==null?'<span class="mut sm">aberto</span><br><button class="btn s" data-a="enc" data-id="${t.id}" style="margin-top:4px">Encerrar</button>':fr(c.r)}<div class="sm mut">${c.pl==null?'':money(c.pl)}</div></div></div>`}
function vList(tp='D'){const sw=tp==='S',ts=S.trades.filter(t=>(t.tipo||'D')===tp&&inPer(t.dt)).sort((a,b)=>b.dt.localeCompare(a.dt));const cr=ts.map(t=>calc(t).r).filter(x=>x!=null);return `<div class="top"><h1>${{D:'Day trade',S:'Swing trade',O:'Opções'}[tp]}</h1><button class="btn" data-a="new" data-tp="${tp}">+ Novo trade</button></div>${perSel()}${filtBar()}${cr.length?`<div class="mut sm" style="margin-top:8px">${cr.length} fechado(s) · ${ts.length-cr.length} aberto(s) · expectância <b class="${cls(avg(cr))}">${fr(avg(cr))}</b></div>`:''}`+(ts.length?(fl(ts).map(card).join('')||'<p class="mut">Nada com esse filtro.</p>'):`<p class="mut">Nenhum trade ainda. ${tp==='O'?'Registre a opção com strike, vencimento e prêmios. O stop em prêmio define 1R.':sw?'Envie a foto do planejamento (entrada, stop e alvos), o stop inicial define 1R.':'Registre o primeiro, com as fotos de entrada e saída, o stop inicial (1R) e o resultado.'}</p>`)}
function sheet(){const t=T,slot=(k,l)=>`<div class="ph"><label>${l}</label><div class="pv">${t[k]?`<img data-img="${t[k]}">`:''}</div><label class="btn s" style="color:var(--tx)">${t[k]?'Trocar':'Adicionar'} foto<input type="file" accept="image/*" hidden data-k="${k}"></label></div>`,n=(k,l,ph='')=>`<label>${l}<input name="${k}" type="number" step="any" inputmode="decimal" value="${esc(t[k])}" placeholder="${ph}"></label>`;
return `<div class="ov"><div class="sh"><div class="top"><h2 style="margin:0">${isNew?'Novo trade':'Editar trade'}${t.tipo==='S'?' (swing)':t.tipo==='O'?' (opção)':''}</h2><button class="x" data-a="close">✕</button></div>
<label>Data e hora<input type="datetime-local" name="dt" value="${t.dt}"></label>
<div class="g2"><label>Ativo<input name="ativo" value="${esc(t.ativo)}" placeholder="WINZ26"></label><div><label>Lado</label>${segs('side',t.side,t.tipo==='O'?[['C','Comprado','g'],['V','Lançado','r']]:[['C','Compra','g'],['V','Venda','r']])}</div></div>
<label>Setup / estratégia<input name="setup" value="${esc(t.setup)}"></label>
<label>Tipo de mercado<select name="mkt">${opt(MK,t.mkt)}</select></label>
${t.tipo==='O'?`<div class="g2"><label>Subjacente<input name="sub" value="${esc(t.sub)}" placeholder="PETR4"></label><label>Call / Put<select name="ot">${opt([['C','Call'],['P','Put']],t.ot||'C')}</select></label></div><div class="g2">${n('strike','Strike')}<label>Vencimento<input type="date" name="venc" value="${esc(t.venc)}"></label></div><div class="g2">${n('spot','Subjacente na entrada')}<label>Estrutura<select name="estr">${opt(ESTR,t.estr)}</select></label></div><div class="mut sm">Em travas e estruturas, use o prêmio líquido: débito = Comprado, crédito = Lançado.</div>`:''}
<div class="g3">${n('entry',t.tipo==='O'?'Prêmio de entrada':'Entrada')}${n('stop',t.tipo==='O'?'Prêmio do stop':'Stop inicial')}${n('target',t.tipo==='O'?'Prêmio alvo 1':t.tipo==='S'?'Alvo 1':'Alvo')}</div>
${t.tipo==='S'||t.tipo==='O'?`<div class="g2">${n('target2','Alvo 2')}${n('target3','Alvo 3')}</div>`:''}<div class="g3">${n('exit',t.tipo==='O'?'Prêmio de saída':'Saída')}${n('qty',t.tipo==='O'?'Qtd. de opções (lote 100)':'Qtd.')}${n('pv',t.tipo==='O'?'Multiplicador (1)':'R$/ponto')}</div>
${n('cost','Custos totais (R$)')}<label>Data e hora da saída<input type="datetime-local" name="dtx" value="${esc(t.dtx)}"></label>
<div class="prev" id="prev"></div>
<h3>Fotos</h3><div class="g2">${t.tipo==='S'||t.tipo==='O'?slot('pplan','Planejamento (entrada, stop, alvos)'):''}${slot('pin','Entrada')}${slot('pout','Saída')}</div>
<h3>Disciplina</h3>
<label>Segui minhas regras?</label>${segs('rules',t.rules,[['s','Sim','g'],['n','Não','r']])}<label>Como eu estava antes de entrar?</label><div class="chips2">${EMO.map((e,i)=>`<button class="${t.emo==i+1?'on':''}" data-seg="emo" data-v="${i+1}">${e}</button>`).join('')}</div>
<label>Erro cometido (erro = não seguir suas regras)<select name="err">${opt(ERR,t.err)}</select></label>
<label>Anotações (por que entrei, o que senti, o que aprendi)<textarea name="nota">${esc(t.nota)}</textarea></label>
<div id="msg" class="r" style="margin:8px 0"></div>
<div class="g2"><button class="btn" data-a="savetrade">Salvar</button>${isNew?'':`<button class="btn d" data-a="deltrade">${delArm?'Confirmar exclusão':'Excluir'}</button>`}</div></div></div>`}
function prev(){const p=$('#prev');if(!p||!T)return;const c=calc(T),d=T.side==='C'?1:-1,e=+T.entry,s=+T.stop;let h='';if(!(e&&s))h='Informe entrada e stop inicial: sem stop não existe 1R.';else{if((e-s)d<=0)h+='⚠ Stop do lado errado da entrada.';h+=1R (risco inicial): <b>${money(c.risk)}</b>;if(c.rr!=null)h+= · R:R planejado <b>${f2(c.rr)}:1</b>${c.rr<3?' <span class="r">(abaixo de 3:1)</span>':''};if(T.tipo==='S'||T.tipo==='O')['target2','target3'].forEach((k,i)=>{if(+T[k])h+= · Alvo ${i+2}: <b>${f2(Math.abs(+T[k]-e)/Math.abs(e-s))}:1</b>});if(c.r!=null)h+=<br>Resultado: <b class="${cls(c.pl)}">${money(c.pl)}</b> = <b class="${cls(c.r)}">${fr(c.r)}</b>${c.r<-1.05?' <span class="r">perda maior que 1R: stop respeitado?</span>':''}}if(T.tipo==='O'&&e&&s){const k=+T.strike,dte=T.venc?Math.round((new Date(T.venc+'T12:00')-new Date(T.dt.slice(0,10)+'T12:00'))/864e5):null;h+='
';if(dte!=null)h+=DTE: <b>${dte}</b> dia(s)${dte<=7?' <span class="r">(vencimento próximo: o tempo corrói o prêmio mais rápido)</span>':''} · ;if(k)h+=Breakeven (opção simples): <b>${f2(T.ot==='P'?k-e:k+e)}</b> · ;h+=Risco: <b>${pc(Math.abs(e-s)/e)}</b> do prêmio}p.innerHTML=h}
function showSheet(){const o=document.querySelector('#sh .ov'),y=o?o.scrollTop:0;$('#sh').innerHTML=T?(QM?qsheet():sheet()):'';const o2=document.querySelector('#sh .ov');if(o2&&y)o2.scrollTop=y;document.body.style.overflow=T?'hidden':'';$('#fab').style.display=T?'none':'';fillImgs();prev()}
function closeSheet(keep){if(T&&!keep)['pin','pout','pplan'].forEach(k=>{if(T[k]&&T[k]!==orig[k])idb('img','delete',T[k])});T=null;QM=0;delArm=0;showSheet()}
/ ---------- Dia ---------- */
function vDia(){const d=S.days[D]||{chk:{}},ts=S.trades.filter(t=>t.dt.slice(0,10)===D).map(t=>({...t,c:calc(t)})),cl=ts.filter(t=>t.c.r!=null),R=sum(cl.map(t=>t.c.r)),P=sum(cl.map(t=>t.c.pl)),er=ts.filter(t=>t.err&&t.err!=='Nenhum').length;
const ta=(k,l,h='')=><label>${l}<textarea data-d="${k}" placeholder="${h}">${esc(d[k])}</textarea></label>;
if(DV==='hist')return vDiaHist();return `Meu dia${diaSeg()}‹Data›${D!==loc().slice(0,10)?'Ir para hoje':''}
Resumo automático${ts.length} trade(s) · ${fr(R)} · ${money(P)} · ${er} erro(s)
☀️ Antes do mercado
Como estou hoje?
${EMO.map((e,i)=><button class="${d.energia==i+1?'on':''}" data-dseg="energia" data-v="${i+1}">${e}</button>).join('')}Tipo de mercado hoje–${opt(MK,d.mkt)}
${ta('plano','Plano do dia','Cenário, níveis, o que vou operar…')}
${ta('pre','Ensaio mental: o que pode dar errado hoje e como vou reagir?')}
✅ Checklist de regras 
${S.rules.length?S.rules.map(r=><label class="ck"><input type="checkbox" data-chk="${r.id}"${d.chk&&d.chk[r.id]?' checked':''}><span>${esc(r.t)}</span></label>).join(''):'Cadastre suas regras na aba Regras.'}
🌙 Depois do mercado (debriefing)
${ta('resumo','Como foi meu dia?')}
Cometi algum erro hoje? (erro = não seguir suas regras)–
${opt([['n','Não — bom trabalho, segui as regras'],['s','Sim']],d.erros)}
${ta('cond','Em que condições errei? When podem se repetir?')}
${ta('prevn','O que vou fazer para não repetir? (ensaiar mentalmente)')}
${ta('bem','O que fiz bem hoje?')}
Nota do dia: ${d.nota===undefined||d.nota===''?'–':esc(d.nota)}
${ta('aprend','Aprendizado principal')}💾 Salvar diaTambém é salvo automaticamente a cada alteração.} function cnt(){const e=$('#cnt');if(!e)return;const c=(S.days[D]||{}).chk||{};e.textContent=Object.values(c).filter(Boolean).length+'/'+S.rules.length} /* ---------- Regras ---------- */ function vRegras(){return Minhas regrasPara Tharp, erro é simplesmente não seguir suas regras escritas. As regras abaixo são sugestões inspiradas no livro: edite ou apague.
Categoria${opt(CATS.map((c,i)=>[i,c]),0)}Nova regraAdicionar regra+CATS.map((c,i)=>{const rs=S.rules.filter(r=>r.cat==i);return rs.length?${c}+rs.map(r=>✕).join(''):''}).join('')} /* ---------- Estatísticas ---------- */ function grp(ts,k,o){const g={};ts.forEach(t=>{(g[t[k]||'—']??=[]).push(t.c.r)});return Object.entries(g).sort((a,b)=>o===1?a[0].localeCompare(b[0]):o?o.indexOf(a[0])-o.indexOf(b[0]):0).map(([k,a])=>${esc(k)}${a.length}${pc(a.filter(x=>x>0).length/a.length)}${f2(avg(a))}R${f2(sum(a))}R).join('')} const tbl=(h,rows)=>${h.map(x=><th>${x}</th>).join('')}${rows}; const qual=x=>x<.16?'Abaixo do tradável':x<.2?'Fraco, mas operável':x<.25?'Médio':x<.3?'Bom':x<.5?'Excelente':x<.7?'Soberbo':'Santo Graal'; function vStats(){const head='<div class="top"><h1>Estatísticas</h1><button class="btn s" data-a="csv" id="csvb">Exportar CSV</button></div>',ts=S.trades.filter(t=>inPer(t.dt)&&(TIPO==='all'||(t.tipo||'D')===TIPO)).map(t=>({...t,c:calc(t)})).filter(t=>t.c.r!=null).sort((a,b)=>a.dt.localeCompare(b.dt)),n=ts.length; if(!n)return head+perSel()+tipoSel()+'<p class="mut">Feche trades com stop e saída para ver expectância, SQN e o custo dos seus erros. Tharp recomenda juntar de 100 a 200 trades.</p>'; const rs=ts.map(t=>t.c.r),m=avg(rs),sd=n>1?Math.sqrt(sum(rs.map(r=>(r-m)**2))/(n-1)):0,ratio=sd?m/sd:0,sqn=ratio*Math.sqrt(Math.min(n,100)),w=rs.filter(r=>r>0),l=rs.filter(r=>r<0),big=l.filter(r=>r<-1.05).length; const cur=[];let c=0,pk=0,dd=0;rs.forEach(r=>{c+=r;cur.push(c);pk=Math.max(pk,c);dd=Math.max(dd,pk-c)}); const dm={};ts.forEach(t=>{const k=(t.dtx||t.dt).slice(0,10);dm[k]=(dm[k]||0)+t.c.pl});const dv=Object.values(dm); const er=ts.filter(t=>t.err&&t.err!=='Nenhum'),ok=ts.filter(t=>!(t.err&&t.err!=='Nenhum')&&t.rules!=='n'),nr=ts.filter(t=>t.rules==='n'); const lo=Math.min(0,...cur),hi=Math.max(0,...cur),sc=v=>90-(v-lo)/((hi-lo)||1)*80,pt=cur.map((v,i)=>${n>1?i/(n-1)300:150},${sc(v)}).join(' '); const WD=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'],ex=ts.map(t=>({...t,wd:WD[new Date(t.dt).getDay()],hr:t.dt.slice(11,13)+'h'}));let mw=0,ml=0,cw=0,cq=0;rs.forEach(r=>{if(r>0){cw++;cq=0}else if(r<0){cq++;cw=0}else{cw=0;cq=0}mw=Math.max(mw,cw);ml=Math.max(ml,cq)}); const kv=(a,b,k='',h='')=>${a}${b}${h}; return head+perSel()+tipoSel()+(n<30?'<div class="warn">Amostra pequena ('+n+' trades): use os números como pista, não como conclusão.</div>':'')+
${kv('Expectância (média de R)',fr(m),cls(m),'quanto você ganha por trade, em R')}${kv('Trades fechados',n,'',pc(w.length/n)+' de acerto')}
${kv('SQN',f2(sqn),'',qual(ratio)+' (média ÷ desvio = '+f2(ratio)+')')}${kv('Desvio-padrão de R',f2(sd)+'R')}
${kv('Média dos ganhos',fr(avg(w)),'g')}${kv('Média das perdas',fr(avg(l)),'r')}
${kv('Maior ganho / perda',fr(Math.max(...rs))+' / '+fr(Math.min(...rs)))}${kv('Perdas acima de 1R',big+' de '+l.length,big>l.length/2?'r':'','se a maioria passa de 1R, o stop não está sendo respeitado')}
${kv('Resultado total',money(sum(ts.map(t=>t.c.pl))),cls(sum(rs)),'custos: '+money(sum(ts.map(t=>+t.cost||0))))}${kv('Drawdown máximo',f2(dd)+'R','r')}
${kv('Dias ganhos / perdidos',dv.filter(x=>x>0).length+' / '+dv.filter(x=>x<0).length)}${kv('Melhor / pior dia',money(Math.max(...dv))+' / '+money(Math.min(...dv)))}
${ring(w.length/n100,'Acerto')}${ring(ok.length/n100,'Regras seguidas','var(--g)')}${ring((n-er.length)/n100,'Sem erro','#e8a317')}Curva de capital (em R)${lineChart('eq',cur,ts.map(t=>fdt(t.dtx||t.dt).slice(0,5)+' '+(t.ativo||'')),v=>fr(v))}Resultado por dia${( ()=>{const dk=Object.keys(dm).sort().slice(-20);return barChart('dia',dk.map(k=>dm[k]),dk.map(k=>k.slice(8)+'/'+k.slice(5,7)))})()}
Disciplina e erros${kv('Eficiência (trades sem erro)',pc((n-er.length)/n),er.length?'':'g')}${kv('Erros a cada 100 trades',f2(er.length/n*100))}
${kv('R líquido dos trades com erro',fr(sum(er.map(t=>t.c.r))),cls(sum(er.map(t=>t.c.r))))}${kv('Expectância: regras seguidas × quebradas',fr(avg(ok.map(t=>t.c.r)))+' × '+fr(avg(nr.map(t=>t.c.r))))}
${er.length?tbl(['Erro','Nº','Acerto','Média','R total'],grp(er,'err')):''}
Por tipo de mercado${tbl(['Mercado','Nº','Acerto','Média','R total'],grp(ts,'mkt'))}
Por setup${tbl(['Setup','Nº','Acerto','Média','R total'],grp(ts,'setup'))}Por dia da semana${tbl(['Dia','Nº','Acerto','Média','R total'],grp(ex,'wd',['Seg','Ter','Qua','Qui','Sex','Sáb','Dom']))}Por horário de entrada${tbl(['Hora','Nº','Acerto','Média','R total'],grp(ex,'hr',1))}Sequências${kv('Maior sequência de ganhos',mw,'g')}${kv('Maior sequência de perdas',ml,'r')}${kv('Sequência atual',cw?cw+' ganho(s)':cq?cq+' perda(s)':'–',cw?'g':cq?'r':'')}Distribuição dos R${hist(rs)}${ts.some(t=>t.tipo==='O')?<h2>Opções por estrutura</h2>${tbl(['Estrutura','Nº','Acerto','Média','R total'],grp(ts.filter(t=>t.tipo==='O'),'estr'))}:''}} async function csv(){const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',h=['data','ativo','lado','setup','mercado','entrada','stop','alvo','saida','qtd','valor_ponto','custos','risco_1R','resultado','R','seguiu_regras','erro','emocional','nota','tipo','alvo2','alvo3','subjacente','call_put','strike','vencimento','estrutura','saida_em'];const rows=S.trades.map(t=>{const c=calc(t);return [t.dt,t.ativo,t.side,t.setup,t.mkt,t.entry,t.stop,t.target,t.exit,t.qty,t.pv,t.cost,c.risk,c.pl,c.r,t.rules,t.err,t.emo,t.nota,t.tipo||'D',t.target2,t.target3,t.sub,t.ot,t.strike,t.venc,t.estr,t.dtx].map(q).join(',')});await saveFile('diario-trades.csv','\ufeff'+h.join(',')+'\n'+rows.join('\n'))} function vGraf(){const op=S.trades.filter(t=>t.tipo==='S'&&calc(t).r==null),w=[...new Set([...(S.watch||[]),...op.map(t=>(t.ativo||'').toUpperCase()).filter(Boolean),...S.trades.filter(t=>t.tipo==='O'&&t.sub&&calc(t).r==null).map(t=>t.sub.toUpperCase())])]; return GráficosGráfico ao vivo não carrega dentro desta página (conexões externas são bloqueadas aqui). O botão abre o gráfico em tempo real no TradingView em outra aba. Ativo fora da B3: digite com a bolsa, ex.: NASDAQ:AAPL.Adicionar ativoAdicionar+(w.length?w.map(a=>{const ls=op.filter(t=>(t.ativo||'').toUpperCase()===a).map(t=>Entrada ${esc(t.entry)} · Stop ${esc(t.stop)}${[t.target,t.target2,t.target3].filter(Boolean).map((x,i)=> · Alvo ${i+1} ${esc(x)}).join('')}).join('<br>');return ${esc(a)}${OPEN[a]?'Fechar':'Ver gráfico aqui'} Gráfico ao vivo ↗${(S.watch||[]).includes(a)? <button class="x" data-a="delw" data-id="${esc(a)}">✕</button>:''}${ls?<div class="mut sm" style="margin-top:6px">${ls}</div>:''}${OPEN[a]?<iframe src="https://tradingview.com{encodeURIComponent(sym(a))}&interval=D&theme=${matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}&locale=br&timezone=America%2FSao_Paulo&allow_symbol_change=1" style="width:100%;height:420px;border:0;margin-top:8px;border-radius:8px"></iframe><div class="mut sm">Quadro em branco ou aviso de símbolo indisponível? Use o botão "Gráfico ao vivo ↗".</div>:''}}).join(''):'<p class="mut">Adicione ativos para acompanhar. Seus swing trades abertos aparecem aqui sozinhos, com entrada, stop e alvos.</p>')} const KV=(a,b,k='',h='')=>${a}${b}${h}`;
function hist(rs){const L=['≤ −2R','−2 a −1R','−1 a 0R','0 a 1R','1 a 2R','2 a 3R','> 3R'],c=L.map(()=>0);rs.forEach(r=>c[r<=-2?0:r<=-1?1:r<0?2:r<1?3:r<2?4:r<=3?5:6]++);const m=Math.max(...c,1);return <div class="card">${L.map((l,i)=>${l}${c[i]}).join('')}</div>}
async function saveFile(n,data,type='text/csv'){try{if(typeof claude!=='undefined'){const dl=await claude.use('downloads');if(dl){await dl.save({filename:n,data});return}}}catch(e){}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=n;document.body.appendChild(a);a.click();a.remove()}
async function backup(){const imgs={};for(const t of S.trades)for(const k of['pin','pout','pplan'])if(t[k]){const b=M[t[k]]||await idb('img','get',t[k]);if(b)imgs[t[k]]=await new Promise(r=>{const f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(b)})}await saveFile('diario-backup-'+loc().slice(0,10)+'.json',JSON.stringify({v:1,S,imgs}),'application/json');S.lastBackup=loc().slice(0,10);save()}
async function restore(f){try{const j=JSON.parse(await f.text()),o=j.S;if(!o)throw 0;for(const[id,u]of Object.entries(j.imgs||{})){const bin=atob(u.split(',')[1]),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);const b=new Blob([a],{type:'image/jpeg'});M[id]=b;await idb('img','put',b,id)}(o.trades||[]).forEach(t=>{const i=S.trades.findIndex(x=>x.id===t.id);i>=0?S.trades[i]=t:S.trades.push(t)});S.days={...S.days,...(o.days||{})};S.ops=unionU(o.ops,S.ops,{});S.lanc=unionU(o.lanc,S.lanc,{});if((o.rules||[]).length)S.rules=o.rules;S.watch=[...new Set([...(S.watch||[]),...(o.watch||[])])];['prop','goals','rev','pn','ax'].forEach(k=>{if(o[k])S[k]={...(S[k]||{}),...o[k]}});if((o.books||[]).length){const m=new Map((S.books||[]).map(b=>[b.id,b]));o.books.forEach(b=>{const x=m.get(b.id);if(!x||(b.u||0)>=(x.u||0))m.set(b.id,b)});S.books=[...m.values()]}save();return 'Backup restaurado: '+(o.trades||[]).length+' trade(s).'}catch(e){return 'Arquivo de backup inválido.'}}
/* ---------- Painel ---------- /
let Z={pct:1},RP='w0',CM=loc().slice(0,7);
const ymd=d=>new Date(d-d.getTimezoneOffset()6e4).toISOString().slice(0,10);
function rng(k){const n=new Date();let a,b,l;if(k[0]==='w'){a=new Date();a.setHours(12);a.setDate(a.getDate()-((a.getDay()+6)%7)-(k==='w1'?7:0));b=new Date(a);b.setDate(b.getDate()+6)}else{const o=k==='m1'?-1:0;a=new Date(n.getFullYear(),n.getMonth()+o,1);b=new Date(n.getFullYear(),n.getMonth()+o+1,0)}return[ymd(a),ymd(b),k+ymd(a)]}
function vPainel(){const P=S.prop||{},G=S.goals||{},f=(k,l)=><label>${l}<input type="number" step="any" inputmode="decimal" data-p="${k}" value="${esc(P[k])}"></label>,z=(k,l)=><label>${l}<input type="number" step="any" inputmode="decimal" data-z="${k}" value="${esc(Z[k])}" ${k==='cap'?placeholder="${esc(P.cap)}":''}></label>;
return <h1>Painel</h1><h2>🛡️ Mesa proprietária</h2><p class="mut sm">Preencha as regras da sua conta. O painel usa seus trades fechados.</p> <div class="g2">${f('cap','Capital inicial (R$)')}${f('meta','Meta de lucro (R$)')}</div><div class="g2">${f('perdaDia','Perda máx. diária (R$)')}${f('ddTotal','Drawdown máx. total (R$)')}</div> <div class="g2">${f('consist','Consistência: maior dia ≤ (% do lucro)')}<label>Tipo de drawdown<select data-p="ddTipo">${opt([['trail','Trailing (do pico)'],['fixo','Fixo (do capital inicial)']],P.ddTipo||'trail')}</select></label></div><div id="pp" style="margin-top:8px"></div> <h2>🎯 Metas de processo</h2><div class="g2"><label>Máx. de trades por dia<input type="number" data-g="maxTr" value="${esc(G.maxTr)}"></label><label>Regras seguidas na semana (%)<input type="number" data-g="regPct" value="${esc(G.regPct)}"></label></div><div id="gg" style="margin-top:8px"></div> <h2>🧮 Tamanho da posição</h2><div class="g2">${z('cap','Capital (R$)')}${z('pct','Risco por trade (%)')}</div><div class="g3">${z('entry','Entrada')}${z('stop','Stop')}${z('pv','R$/ponto')}</div><div class="prev" id="zz"></div><div class="mut sm">R$/ponto: WIN 0,20 · WDO 10 · ações 1.</div> <h2>💾 Backup completo</h2><p class="mut sm">Salva trades, fotos, dias, regras e painel em um arquivo .json. Restaurar mescla com o que já existe neste aparelho.</p><div class="g2"><button class="btn" data-a="bk">Exportar backup</button><label class="btn s" style="margin:0;text-align:center;color:var(--tx)">Restaurar backup<input type="file" accept=".json,application/json" hidden id="bkf"></label></div><div id="bm" class="mut sm" style="margin-top:8px">${S.lastBackup?'Último backup: '+S.lastBackup.split('-').reverse().join('/'):'Nenhum backup feito ainda.'}</div>}
function ppOut(){const e=$('#pp');if(!e)return;const P=S.prop||{},cl=S.trades.map(t=>({...t,c:calc(t)})).filter(t=>t.c.pl!=null).sort((a,b)=>a.dt.localeCompare(b.dt)),cap=+P.cap||0,td=loc().slice(0,10),dm={};let eq=cap,pk=cap;cl.forEach(t=>{eq+=t.c.pl;pk=Math.max(pk,eq);const d=(t.dtx||t.dt).slice(0,10);dm[d]=(dm[d]||0)+t.c.pl});
const tot=eq-cap,ddv=P.ddTipo==='fixo'?Math.max(0,cap-eq):pk-eq,hoje=dm[td]||0,dv=Object.values(dm),best=dv.length?Math.max(...dv):0,L=n=>+P[n]||0;
const bar=(v,max,inv)=>{const p=max>0?Math.min(100,Math.max(0,v/max100)):0,c=inv?(p>=80?'var(--r)':p>=50?'#e8a317':'var(--g)'):'var(--ac)';return <div style="height:8px;background:var(--bg);border-radius:6px;margin:4px 0;border:1px solid var(--bd)"><div style="height:100%;width:${p}%;background:${c};border-radius:6px"></div></div>},row=(t,m,sb,b)=><div class="card"><b>${t}</b> <span class="mut sm">${sb}</span><div>${m}</div>${b}</div>;let h='';
if(L('perdaDia')){const u=Math.max(0,-hoje);h+=row('Perda diária hoje',${money(u)} de ${money(L('perdaDia'))},'restam '+money(Math.max(0,L('perdaDia')-u)),bar(u,L('perdaDia'),1))+(u>=L('perdaDia').8?'⚠ Perto (ou acima) do limite de perda diária: pare de operar hoje.':'')}
if(L('ddTotal'))h+=row('Drawdown '+(P.ddTipo==='fixo'?'fixo':'trailing'),${money(ddv)} de ${money(L('ddTotal'))},'restam '+money(Math.max(0,L('ddTotal')-ddv)),bar(ddv,L('ddTotal'),1));
if(L('meta'))h+=row('Meta de lucro',${money(tot)} de ${money(L('meta'))},pc(Math.max(0,tot)/L('meta')),bar(Math.max(0,tot),L('meta')));
if(L('consist')&&tot>0){const sh=best/tot100;h+=row('Consistência',Maior dia: ${money(best)} = ${f2(sh)}% do lucro,'limite '+L('consist')+'%',bar(sh,L('consist'),1))+(sh>L('consist')?<div class="warn">⚠ Maior dia acima do limite. O lucro total precisa chegar a ${money(best/(L('consist')/100))} (sem novo dia maior).</div>:'')}
e.innerHTML=h||'Preencha os limites acima para ver o painel.'}
function ggOut(){const e=$('#gg');if(!e)return;const G=S.goals||{},td=loc().slice(0,10),n=S.trades.filter(t=>t.dt.slice(0,10)===td).length,[a,b]=rng('w0'),w=S.trades.filter(t=>{const d=t.dt.slice(0,10);return d>=a&&d<=b}),ok=w.filter(t=>t.rules!=='n'&&(!t.err||t.err==='Nenhum')).length,ds=[...new Set([...S.trades.map(t=>t.dt.slice(0,10)),...Object.keys(S.days).filter(d=>S.days[d].resumo||S.days[d].erros)])].sort(),clean=d=>!S.trades.some(t=>t.dt.slice(0,10)===d&&(t.rules==='n'||(t.err&&t.err!=='Nenhum')))&&(S.days[d]||{}).erros!=='s';let run=0,best=0;ds.forEach(d=>{run=clean(d)?run+1:0;best=Math.max(best,run)});const over=+G.maxTr&&n>+G.maxTr,pr=w.length?ok/w.length100:null;
e.innerHTML=<div class="kv">${KV('Dias seguidos sem erro',run,run?'g':'','melhor: '+best)}${KV('Trades hoje',n+(+G.maxTr?' / '+G.maxTr:''),over?'r':'',over?'acima do limite: pare':'')}${KV('Regras seguidas (semana)',pr==null?'–':Math.round(pr)+'%',pr!=null&&+G.regPct&&pr<+G.regPct?'r':'g',+G.regPct?'meta '+G.regPct+'%':'')}</div>}
function zzOut(){const e=$('#zz');if(!e)return;const P=S.prop||{},cap=+(Z.cap||P.cap),pct=+Z.pct,en=+Z.entry,st=+Z.stop,pv=+Z.pv||1;if(!(cap&&pct&&en&&st&&en!==st)){e.innerHTML='Informe capital, % de risco, entrada e stop.';return}const R=cappct/100,ru=Math.abs(en-st)pv,q=Math.floor(R/ru);e.innerHTML=Risco por trade (1R): <b>${money(R)}</b><br>Risco por unidade: ${money(ru)}<br>Tamanho sugerido: <b>${q}</b> ${q<1?'<span class="r">(stop largo demais para esse risco)</span>':
Risco real: ${money(qru)} (${f2(qru/cap100)}% do capital)}}
/ ---------- Revisão ---------- */
const MES=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
function cal(){const[y,m]=CM.split('-').map(Number),dim=new Date(y,m,0).getDate(),off=new Date(y,m-1,1).getDay(),dm={};S.trades.forEach(t=>{const c=calc(t);if(c.pl!=null&&(t.dtx||t.dt).slice(0,7)===CM){const d=(t.dtx||t.dt).slice(0,10);dm[d]=(dm[d]||0)+c.pl}});
let h=<div class="top"><button class="btn s" data-a="cprev">‹</button><b>${MES[m-1]} ${y}</b><button class="btn s" data-a="cnext">›</button></div><div class="cal">${['D','S','T','Q','Q','S','S'].map(x=>${x}).join('')}+''.repeat(off);for(let i=1;i<=dim;i++){const d=${CM}-${String(i).padStart(2,'0')},v=dm[d];h+=<button data-a="cday" data-id="${d}" class="${v>0?'cg':v<0?'cr':''}">${i}<span>${v==null?'':Math.round(v)}</span></button>}return h+'Verde: dia positivo · Vermelho: dia negativo (R$). Toque no dia para abrir o registro.'}
function vRev(){const[a,b,key]=rng(RP),ts=S.trades.map(t=>({...t,c:calc(t)})).filter(t=>{const d=t.dt.slice(0,10);return d>=a&&d<=b&&t.c.r!=null}),n=ts.length,rs=ts.map(t=>t.c.r),rv=(S.rev||{})[key]||{},ds=Object.keys(S.days).filter(d=>d>=a&&d<=b),nt=ds.map(d=>S.days[d].nota).filter(x=>x!==''&&x!=null).map(Number),eg={};ts.filter(t=>t.err&&t.err!=='Nenhum').forEach(t=>{eg[t.err]=(eg[t.err]||0)+t.c.r});const top=Object.entries(eg).sort((x,y)=>x[1]-y[1])[0],ta=(k,l)=><label>${l}<textarea data-rv="${k}">${esc(rv[k])}</textarea></label>;
return <h1>Revisão</h1>${cal()}<h2>Revisão do período</h2><label>Período<select id="rp">${opt([['w0','Esta semana'],['w1','Semana passada'],['m0','Este mês'],['m1','Mês passado']],RP)}</select></label><div class="mut sm">${a.split('-').reverse().join('/')} a ${b.split('-').reverse().join('/')}</div>+(n?<div class="kv" style="margin-top:8px">${KV('Trades',n,'',pc(rs.filter(r=>r>0).length/n)+' de acerto')}${KV('R total',fr(sum(rs)),cls(sum(rs)),'expectância '+fr(avg(rs)))}${KV('Resultado',money(sum(ts.map(t=>t.c.pl))),cls(sum(rs)))}${KV('Regras seguidas',pc(ts.filter(t=>t.rules!=='n').length/n))}${KV('Nota média do dia',nt.length?f2(avg(nt)):'–')}${KV('Dias registrados',ds.length)}</div>${top?Erro mais caro: ${esc(top[0])} ${fr(top[1])}:'<div class="card g">Nenhum erro registrado no período 👏</div>'}' : '<p class="mut">Sem trades fechados neste período.</p>')+ta('repetir','O que vou repetir (o que funcionou)?')+ta('parar','O que vou parar de fazer?')+ta('plano','Foco para o próximo período')} function vTrades(tp='D'){if(tp==='D')return vList(tp);const vw=VW[tp]||'ab',ts=S.trades.filter(t=>t.tipo===tp&&inPer(t.dt)),ab=ts.filter(isOpen).sort((a,b)=>b.dt.localeCompare(a.dt)); return ${tp==='O'?'Opções':'Swing trade'}+ Novo tradeAbertas (${ab.length})Performance${tp==='S'?<button class="btn ${vw==='sc'?'':'s'}" data-a="vw" data-tp="S" data-id="sc">Scanner</button>:''}${vw==='sc'?'':perSel()}${vw==='pf'?filtBar():''}+(vw==='sc'&&tp==='S'?vScan():vw==='ab'?(ab.length?ab.map(card).join(''):Nenhuma posição aberta. ${tp==='O'?'Registre a montagem com strike, vencimento e prêmio de entrada.':'Registre a entrada com o planejamento (entrada, stop e alvos).'} Depois use o botão Encerrar quando sair.):perfView(ts))} function perfView(ts){const cl=fl(ts).map(t=>({...t,c:calc(t)})).filter(t=>t.c.r!=null).sort((a,b)=>(b.dtx||b.dt).localeCompare(a.dtx||a.dt));if(!cl.length)return '<p class="mut">Nenhuma operação operação encerrada no período.</p>';const rs=cl.map(t=>t.c.r),P=sum(cl.map(t=>t.c.pl)); return ${KV('Resultado',money(P),cls(P),cl.length+' operação(ões)')}${KV('R total',fr(sum(rs)),cls(sum(rs)),'expectância '+fr(avg(rs)))}${KV('Acerto',pc(rs.filter(r=>r>0).length/rs.length))}${KV('Maior ganho / perda',fr(Math.max(...rs))+' / '+fr(Math.min(...rs)))}AtivoEntradaSaídaResultado${cl.map(t=><tr data-a="edit" data-id="${t.id}" style="cursor:pointer"><td>${esc(t.ativo)||'—'}<div class="mut sm">${fdt(t.dtx||t.dt).slice(0,5)}${t.tipo==='O'&&t.strike?' · '+(t.ot==='P'?'Put':'Call')+' '+esc(t.strike):''}</div></td><td>${esc(t.entry)}</td><td>${esc(t.exit)}</td><td class="${cls(t.c.pl)}">${money(t.c.pl)}<div class="sm">${fr(t.c.r)}</div></td></tr>).join('')}} function qsheet(){const t=T;return Encerrar posição✕${esc(t.ativo)||'—'} · ${t.tipo==='O'?(t.side==='C'?'Comprado':'Lançado'):(t.side==='C'?'Compra':'Venda')}Entrada ${esc(t.entry)} · Stop ${esc(t.stop)} · Qtd. ${esc(t.qty)}
\({t.tipo==='O'?'Prêmio de saída':'Preço de saída'}<input name="exit" type="number" step="any" inputmode="decimal" value="\){esc(t.exit)}">
Custos totais (R$)Data e hora da saída
Foto da saída${t.pout?<img data-img="${t.pout}">:''}${t.pout?'Trocar':'Adicionar'} foto
Segui minhas regras?
${segs('rules',t.rules,[['s','Sim','g'],['n','Não','r']])}Erro cometido${opt(ERR,t.err)}
Anotações${esc(t.nota)}
Encerrar posição`}
function zoom(src){const l=$('#lb');l.innerHTML=<button class="x" data-a="lbx" style="position:fixed;top:calc(8px + env(safe-area-inset-top,0px));right:12px;color:#fff;font-size:30px;z-index:2">✕</button><img src="${src}" style="width:100%;display:block;margin:auto">;l.style.display='block'}
function bkBanner(){if(tab==='painel'||!S.trades.length)return;if(SESS&&S.lastSyncAt&&Date.now()-S.lastSyncAt<3864e5)return;const d=S.lastBackup?Math.floor((Date.now()-new Date(S.lastBackup+'T12:00'))/864e5):null;if(d!=null&&d<=7)return;$('#app').insertAdjacentHTML('afterbegin',<div class="warn" style="margin-bottom:8px">💾 ${d==null?'Você ainda não fez backup.':'Último backup há '+d+' dias.'} Fotos e trades ficam só neste aparelho. <button class="btn s" data-a="gopainel" style="margin-left:6px">Fazer backup</button></div>)}
function vHome(){const td=loc().slice(0,10),hj=S.trades.map(t=>({...t,c:calc(t)})).filter(t=>t.c.pl!=null&&(t.dtx||t.dt).slice(0,10)===td),P=sum(hj.map(t=>t.c.pl)),R=sum(hj.map(t=>t.c.r)),ab=S.trades.filter(isOpen).sort((a,b)=>b.dt.localeCompare(a.dt)),nck=Object.values((S.days[td]||{}).chk||{}).filter(Boolean).length,ven=ab.filter(t=>t.tipo==='O'&&t.venc).map(t=>({t,d:Math.round((new Date(t.venc+'T12:00')-new Date(td+'T12:00'))/864e5)})).filter(x=>x.d<=7).sort((a,b)=>a.d-b.d);
return ${hero(P,R,hj.length,ab.length,nck)}${posso(hj,P,nck)}<h2>Radar de mercado</h2><div id="radar" style="min-height:120px"></div>${ven.length?'<h2>⏳ Vencimentos próximos</h2>'+ven.map(x=>${esc(x.t.ativo)} · ${x.d<0?'venceu há '+(-x.d)+' dia(s)':x.d===0?'vence hoje':'vence em '+x.d+' dia(s)'}).join(''):''}<h2>Posições abertas (${ab.length})</h2>${ab.length?ab.map(card).join(''):'<p class="mut">Nenhuma posição aberta.</p>'}<h2>Limites da mesa</h2><div id="pp"></div><h2>Metas de processo</h2><div id="gg"></div>${calMes()}<div class="g2" style="margin-top:12px"><button class="btn" data-a="new" data-tp="D">+ Day trade</button><button class="btn s" data-a="gotab" data-id="dia">Abrir o dia</button></div>}
/ ---------- Nuvem (Supabase) ---------- */
const ls={get(k){try{return JSON.parse(localStorage.getItem(k))}catch(e){return null}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}},del(k){try{localStorage.removeItem(k)}catch(e){}}};
const cfg=()=>window.SUPA_URL&&window.SUPA_KEY?{url:String(window.SUPA_URL).replace(//$/,''),key:window.SUPA_KEY}:ls.get('diario-cfg');
const hm=(t=Date.now())=>new Date(t).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
const em=e=>{const m=String(e&&e.message||e);return /Invalid login/i.test(m)?'E-mail ou senha incorretos.':/not confirmed/i.test(m)?'Confirme seu e-mail antes de entrar.':/already registered/i.test(m)?'E-mail já cadastrado: use Entrar.':/Failed to fetch|NetworkError|Load failed/i.test(m)?'Sem conexão com a internet.':/at least/i.test(m)?'A senha precisa ter pelo menos 6 caracteres.':m};
const seedRules=()=>{S.rules=SEED.map(([cat,t])=>({id:uid(),cat,t}))};
async function rq(path,o={},auth=true){const c=cfg();if(!c)throw new Error('Configure o Supabase.');if(auth)await tok();const bt=o.tok||(auth&&SESS?SESS.at:/^eyJ/.test(c.key)?c.key:''),h={apikey:c.key,...(bt?{Authorization:'Bearer '+bt}:{}),...(o.headers||{})},r=await fetch(c.url+path,{...o,headers:h});if(!r.ok){let m='';try{const j=await r.json();m=j.msg||j.message||j.error_description||j.error||''}catch(e){}const x=new Error(m||('Erro '+r.status));x.status=r.status;throw x}return r}
function setSess(j,email){SESS={at:j.access_token,rt:j.refresh_token,exp:Date.now()+(j.expires_in||3
